// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from '@rocicorp/zero';
import { createBuilder } from '@rocicorp/zero';

const accountTable = {
  name: 'account',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    accountId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'account_id',
    },
    userId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'user_id',
    },
  },
  primaryKey: ['id'],
} as const;
const docTable = {
  name: 'doc',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    title: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    content: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    ownerId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'owner_id',
    },
  },
  primaryKey: ['id'],
} as const;
const docOperationTable = {
  name: 'docOperation',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    docId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'doc_id',
    },
    operation: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
  },
  primaryKey: ['id'],
  serverName: 'doc_operation',
} as const;
const userTable = {
  name: 'user',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    image: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ['id'],
} as const;
const accountRelationships = {
  user: [
    {
      sourceField: ['userId'],
      destField: ['id'],
      destSchema: 'user',
      cardinality: 'one',
    },
  ],
} as const;
const docOperationRelationships = {
  doc: [
    {
      sourceField: ['docId'],
      destField: ['id'],
      destSchema: 'doc',
      cardinality: 'one',
    },
  ],
} as const;
const docRelationships = {
  owner: [
    {
      sourceField: ['ownerId'],
      destField: ['id'],
      destSchema: 'user',
      cardinality: 'one',
    },
  ],
  operations: [
    {
      sourceField: ['id'],
      destField: ['docId'],
      destSchema: 'docOperation',
      cardinality: 'many',
    },
  ],
} as const;
const userRelationships = {
  accounts: [
    {
      sourceField: ['id'],
      destField: ['userId'],
      destSchema: 'account',
      cardinality: 'many',
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    account: accountTable,
    doc: docTable,
    docOperation: docOperationTable,
    user: userTable,
  },
  relationships: {
    account: accountRelationships,
    docOperation: docOperationRelationships,
    doc: docRelationships,
    user: userRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "account" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["account"] instead from "@rocicorp/zero".
 */
export type Account = Row['account'];
/**
 * Represents a row from the "doc" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["doc"] instead from "@rocicorp/zero".
 */
export type Doc = Row['doc'];
/**
 * Represents a row from the "docOperation" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["docOperation"] instead from "@rocicorp/zero".
 */
export type DocOperation = Row['docOperation'];
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["user"] instead from "@rocicorp/zero".
 */
export type User = Row['user'];

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use `zql` instead.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' {
  interface DefaultTypes {
    schema: Schema;
  }
}
